// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v4.22.0
// source: searchresult_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publisher     string `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
	PublisherDate string `protobuf:"bytes,2,opt,name=publisher_date,json=publisherDate,proto3" json:"publisher_date,omitempty"`
	PublishField  string `protobuf:"bytes,3,opt,name=publish_field,json=publishField,proto3" json:"publish_field,omitempty"`
	Context       string `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_searchresult_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_searchresult_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_searchresult_message_proto_rawDescGZIP(), []int{0}
}

func (x *SearchResult) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *SearchResult) GetPublisherDate() string {
	if x != nil {
		return x.PublisherDate
	}
	return ""
}

func (x *SearchResult) GetPublishField() string {
	if x != nil {
		return x.PublishField
	}
	return ""
}

func (x *SearchResult) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

var File_searchresult_message_proto protoreflect.FileDescriptor

var file_searchresult_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x72, 0x44, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_searchresult_message_proto_rawDescOnce sync.Once
	file_searchresult_message_proto_rawDescData = file_searchresult_message_proto_rawDesc
)

func file_searchresult_message_proto_rawDescGZIP() []byte {
	file_searchresult_message_proto_rawDescOnce.Do(func() {
		file_searchresult_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_searchresult_message_proto_rawDescData)
	})
	return file_searchresult_message_proto_rawDescData
}

var file_searchresult_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_searchresult_message_proto_goTypes = []interface{}{
	(*SearchResult)(nil), // 0: proto.searchResult
}
var file_searchresult_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_searchresult_message_proto_init() }
func file_searchresult_message_proto_init() {
	if File_searchresult_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_searchresult_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_searchresult_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_searchresult_message_proto_goTypes,
		DependencyIndexes: file_searchresult_message_proto_depIdxs,
		MessageInfos:      file_searchresult_message_proto_msgTypes,
	}.Build()
	File_searchresult_message_proto = out.File
	file_searchresult_message_proto_rawDesc = nil
	file_searchresult_message_proto_goTypes = nil
	file_searchresult_message_proto_depIdxs = nil
}
