// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v4.22.0
// source: searchpolicy_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchPolicyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     *UserData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Keywords []string  `protobuf:"bytes,2,rep,name=keywords,proto3" json:"keywords,omitempty"`
}

func (x *SearchPolicyRequest) Reset() {
	*x = SearchPolicyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_searchpolicy_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPolicyRequest) ProtoMessage() {}

func (x *SearchPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_searchpolicy_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPolicyRequest.ProtoReflect.Descriptor instead.
func (*SearchPolicyRequest) Descriptor() ([]byte, []int) {
	return file_searchpolicy_service_proto_rawDescGZIP(), []int{0}
}

func (x *SearchPolicyRequest) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SearchPolicyRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type SearchPolicyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Searcher string          `protobuf:"bytes,1,opt,name=searcher,proto3" json:"searcher,omitempty"`
	Results  []*SearchResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *SearchPolicyResponse) Reset() {
	*x = SearchPolicyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_searchpolicy_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPolicyResponse) ProtoMessage() {}

func (x *SearchPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searchpolicy_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPolicyResponse.ProtoReflect.Descriptor instead.
func (*SearchPolicyResponse) Descriptor() ([]byte, []int) {
	return file_searchpolicy_service_proto_rawDescGZIP(), []int{1}
}

func (x *SearchPolicyResponse) GetSearcher() string {
	if x != nil {
		return x.Searcher
	}
	return ""
}

func (x *SearchPolicyResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_searchpolicy_service_proto protoreflect.FileDescriptor

var file_searchpolicy_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x22,
	0x61, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x32, 0x62, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_searchpolicy_service_proto_rawDescOnce sync.Once
	file_searchpolicy_service_proto_rawDescData = file_searchpolicy_service_proto_rawDesc
)

func file_searchpolicy_service_proto_rawDescGZIP() []byte {
	file_searchpolicy_service_proto_rawDescOnce.Do(func() {
		file_searchpolicy_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_searchpolicy_service_proto_rawDescData)
	})
	return file_searchpolicy_service_proto_rawDescData
}

var file_searchpolicy_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_searchpolicy_service_proto_goTypes = []interface{}{
	(*SearchPolicyRequest)(nil),  // 0: proto.SearchPolicyRequest
	(*SearchPolicyResponse)(nil), // 1: proto.SearchPolicyResponse
	(*UserData)(nil),             // 2: proto.UserData
	(*SearchResult)(nil),         // 3: proto.searchResult
}
var file_searchpolicy_service_proto_depIdxs = []int32{
	2, // 0: proto.SearchPolicyRequest.data:type_name -> proto.UserData
	3, // 1: proto.SearchPolicyResponse.results:type_name -> proto.searchResult
	0, // 2: proto.SearchPolicyService.SearchPolicy:input_type -> proto.SearchPolicyRequest
	1, // 3: proto.SearchPolicyService.SearchPolicy:output_type -> proto.SearchPolicyResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_searchpolicy_service_proto_init() }
func file_searchpolicy_service_proto_init() {
	if File_searchpolicy_service_proto != nil {
		return
	}
	file_userdata_message_proto_init()
	file_searchresult_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_searchpolicy_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPolicyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_searchpolicy_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPolicyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_searchpolicy_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_searchpolicy_service_proto_goTypes,
		DependencyIndexes: file_searchpolicy_service_proto_depIdxs,
		MessageInfos:      file_searchpolicy_service_proto_msgTypes,
	}.Build()
	File_searchpolicy_service_proto = out.File
	file_searchpolicy_service_proto_rawDesc = nil
	file_searchpolicy_service_proto_goTypes = nil
	file_searchpolicy_service_proto_depIdxs = nil
}
